### ISSUE TITLE
Timestamp on console logs

### ISSUE THREAD

**Issue by swithinfoote** [apigee/microgateway-core#100]
Hi there, when logging to console the microgateway does not record a time stamp. The relevant piece of code is in lib/logging.js - line 232.
`const preamble = logToConsole ? '' : Date.now() + ' '`
By removing _logToConsole ? '' :_ I can get it to log the unix timestamp to the console. Can you explain why this logic is in there and if it is possible to remove it or add a config parameter for logging timestamp when using console logging?
Cheers, Swithin.

**Comment by srinandan** [comment]
Sorry for the late response. I'll fix this in the next release.

**Comment by theganyo** [comment]
Closing for lack of updates. It looks like the code has been rewritten and the original description is no longer valid. Please reopen with more detail if still valid.
