### ISSUE TITLE
Plugins append to response body instead of replacing.

### ISSUE THREAD

**Issue by mdobson** [apigee/microgateway-core#17]
I'm working through the first custom plugin tutorial for edgemicro found here: http://docs.apigee.com/microgateway/latest/develop-plugins. I've run into some peculiar behavior though.

Here is my plugin code:

```
'use strict';

var debug = require('debug')('plugin:response-override');


module.exports.init = function(config, logger, stats) {


  return {

    ondata_response: function(req, res, data, next) {
      debug('***** plugin ondata_response');
      next(null, null);
    },

    onend_response: function(req, res, data, next) {
      debug('***** plugin onend_response');
      next(null, "Hello, World!\n\n");
    }
  };
}
```

Instead of replacing the response body with custom text. My plugin simply appends the text to the current response body.

```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
date: Mon, 10 Oct 2016 14:31:11 GMT
etag: W/"1cd-igZDs61JMAiJo6ZDx/UFDQ"
x-powered-by: Apigee
x-response-time: 635
Connection: keep-alive
Transfer-Encoding: chunked

{"headers":{"host":"mocktarget.apigee.net","accept":"*/*","user-agent":"curl/7.43.0","via":"undefined1.1 localhost","x-authorization-claims":"eyJzY29wZXMiOltdfQ==","x-forwarded-host":"undefinedlocalhost:8000","x-request-id":"d68c00d0-8ef5-11e6-8c68-5758f301a7dc.30bc13b0-8ef6-11e6-8c68-5758f301a7dc","x-forwarded-for":"undefined::1, 68.49.164.231","x-forwarded-port":"80","x-forwarded-proto":"http","connection":"keep-alive"},"method":"GET","url":"/","body":""}Hello, World!
```

**Comment by kevinswiber** [comment]
@F1ERRO and I talked about this yesterday.

1. Passing `null` as the second parameter of the `next` function in `ondata_response` streams the original `data` chunk.
2. The `data` parameter is actually an object of `pluginOptions`.  To access the chunk, you have to use `data.data`.
3. The second parameter of `next` used in the `onend_response` function appends to the end of the stream, because the data elements have already been pushed to the stream in `ondata_response`.

**Comment by kevinswiber** [comment]
To get your example to work, you need to pass an empty buffer like so:

```js
'use strict';

var debug = require('debug')('plugin:response-override');

var emptyBuffer = new Buffer(0);

module.exports.init = function(config, logger, stats) {


  return {

    ondata_response: function(req, res, data, next) {
      debug('***** plugin ondata_response');
      next(null, emptyBuffer);
    },

    onend_response: function(req, res, data, next) {
      debug('***** plugin onend_response');
      next(null, "Hello, World!\n\n");
    }
  };
}
```

**Comment by kevinswiber** [comment]
@WWitman FYI: Docs are totally borked for plugins, but that's okay for now, because the actual plugin functionality appears to have never worked properly in v2.  We're going to look at what we need to do to fix or redesign the broken implementation and will get back to you.

**Comment by mdobson** [comment]
Yeah. There are definitely a few issues going on here. At least one issue I
have a fix for. I've got a way to pass null instead of an empty buffer to
override a response body.

-Matt

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!
<http://adapt.apigee.com>

**Comment by dteirney** [comment]
We're about to implement a plugin. What do we need to know about how to do this if the "documentation is borked".

**Comment by mdobson** [comment]
See @kevinswiber s work around if you need to do body transformation currently. In a release coming out this week we'll have fixes in EM to actually make the documentation correct again.
