### ISSUE TITLE
Allow rewrite of target url

### ISSUE THREAD

**Issue by srinandan** [apigee/microgateway-core#26]
Provide a mechanism for custom plugins to rewrite/change the target endpoint. We need to discuss how TLS parameters will be passed (if set). Will those still come from the config.yaml file?

**Comment by kenigeer** [comment]
My PR #13 includes 4009225ab80b86f8d50fbf2ea424a900b15953f9 which has change for Cloud Foundry in this general direction.

**Comment by F1ERRO** [comment]
03445b fixes this

modify req.targetHostname and req.targetPath

**Comment by asnowfix** [comment]
Is this feature dropped?

**Comment by F1ERRO** [comment]
No.  In the latest version (2.2.4-beta) the target endpoint can be dynamically changed inside a plugin by modifying either or both of 

req.targetHostname (i.e http://mocktarget.apigee.net)
req.targetPath (i.e /users/id/123)
