### ISSUE TITLE
Issue with wildcard support in 2.4.5-beta

### ISSUE THREAD

**Issue by jaskarangump** [apigee/microgateway-core#80]
We created a plugin to set targetpath same as request url. This allowed appropriate path to be sent to backend.

**Test Execution results**
Three proxies were created as follows - 
1. edgemicro_abc - /abc
2. edgemicro_abc__ - /abc/*
3. edgemicro_abc_xyz - /abc/*/xyz

Request path: /abc
Proxy: edgemicro_abc
Target: /abc
Test Status: **PASS**

Request path: /abc?x=y
Proxy: edgemicro_abc
Target: N/A. Proxy returned 403
Test Status: **FAIL**

Request path: /abc/123
Proxy: edgemicro_abc__
Target: /abc/123
Test Status: **PASS**

Request path: /abc/123?x=y
Proxy: edgemicro_abc__
Target: /abc/123?x=y
Test Status: **PASS**

Request path: /abc/123/xyz
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz
Test Status: **PASS**

Request path: /abc/123/xyz?x=y
Proxy: edgemicro_abc__xyz
Target: N/A. Proxy returned 403
Test Status: **FAIL**

Request path: /abc/123/11
Proxy: edgemicro_abc__
Target: /abc/123/11
Test Status: **PASS**

Request path: /abc/123/11?x=y
Proxy: edgemicro_abc__
Target: /abc/123/11?x=y
Test Status: **PASS**

Request path: /abc/123/xyz/11
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz/11
Test Status: **PASS**

Request path: /abc/123/xyz/11?x=y
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz/11?x=y
Test Status: **PASS**

**Comment by mdobson** [comment]
@jaskarangump Where is the 403 coming from? We don't issue 403 in microgateway.
