### ISSUE TITLE
Protocol not supported error on plugin redirecting to HTTPS target

### ISSUE THREAD

**Issue by victoranaylton** [apigee/microgateway-core#81]
Hello All,

I have a plugin that overrides the target URL for one set in the plugin configuration.

On this plugin, i'm changing the `req.targetHostname and req.targetPath` and, if the target protocol is https, i'm also changing the `req.targetSecure` to `true` and the `req.targetPort` to 443

```js
req.targetHostname = targetPathHostname // new target hostname
req.targetPath = targetPath // new target path

if (targetPathProtocol === 'https') {
  req.targetSecure = true
  req.targetPort = 443
} 
```
With this, when the request is executed, i'm getting the following error:

```sh
curl -i http://localhost:8000/health
HTTP/1.1 500 Internal Server Error
Date: Wed, 24 May 2017 12:57:14 GMT
Connection: keep-alive
Content-Length: 67

{"message":"Protocol \"https:\" not supported. Expected \"http:\""}
```

Just to be sure, i've configured my edgemicro instance to work with ssl but the error was the same:

```sh
curl -i https://localhost:8000/health
HTTP/1.1 500 Internal Server Error
Date: Wed, 24 May 2017 12:57:14 GMT
Connection: keep-alive
Content-Length: 67

{"message":"Protocol \"https:\" not supported. Expected \"http:\""}
```

Is it possible to do this? Change the target URL and also change from HTTP to HTTPS?

I'm using the following versions:
```
current nodejs version is v6.10.0
current edgemicro version is 2.4.5-beta
```

**Comment by mdobson** [comment]
While it is possible to do this. It's not recommended. Here is one of two ways to make this work.

Set the target for your proxy to be an https proxy in edge. This will correctly configure everything internally. 

You can also attempt to replace the agent used to make requests. You simply create an instance of https.Agent and assign it as the proxy agent. Brief code snippet below to document how to possibly do this.

```javascript
var https = require('https');

//...elided 
onrequest: function(req, res, next) {
  var agent = new https.Agent({
    keepAlive: true
  })

  res.proxy.agent = agent;
//...elided
}

```

**Comment by victoranaylton** [comment]
Just to add more information
Found this debugging the execution:

In the **[plugins-middleware.js](https://github.com/apigee/microgateway-core/blob/master/lib/plugins-middleware.js)**
```js
const proxy = sourceResponse.proxy; // get the proxy from sourceResponse

...  

var httpLibrary = http;
if (sourceRequest.targetSecure || proxy.secureHttpProxy) {
  httpLibrary = https; 
}
// As the plugin sets the targetSecure to "true", the httpLibrary will be "https"

var targetRequestOptions = {
  hostname: sourceRequest.targetHostname,
  port: parseInt(sourceRequest.targetPort),
  path: sourceRequest.targetPath,
  method: sourceRequest.method,
  headers: target_headers, 
  agent: proxy.agent // this agent has a "protocol" property with "http" as value
};

...

const targetRequest = httpLibrary.request(targetRequestOptions,
  (targetResponse) => cb(null, targetResponse)); // execute the request passing the targetRequestOptions above
``` 

the execution will land in the following code in the **_http_client.js** file 

``` js
 var protocol = options.protocol || defaultAgent.protocol; // protocol will be "https"
 var expectedProtocol = defaultAgent.protocol;
 if (self.agent && self.agent.protocol) // self.agent is the same targetRequestOptions.agent
    expectedProtocol = self.agent.protocol; // expectedProtocol will be set to "http"

  if (options.path && / /.test(options.path)) {
    throw new TypeError('Request path contains unescaped characters');
  } else if (protocol !== expectedProtocol) { //this will be true:  Error!!
    throw new Error('Protocol "' + protocol + '" not supported. ' +
                    'Expected "' + expectedProtocol + '"');
  }
```

**Comment by victoranaylton** [comment]
@mdobson Thanks for the answer!
I'll try as you suggested.

**Comment by victoranaylton** [comment]
@mdobson It worked as you said, thanks again!

**Comment by mdobson** [comment]
Great. One small change. You'll want to create an https.Agent outside of the onrequest function, or you'll get some performance issues down the line.

```javascript
var https = require('https');
var agent = new https.Agent({
  keepAlive: true
})
//...elided 
onrequest: function(req, res, next) {
  res.proxy.agent = agent;
//...elided
}
```

**Comment by victoranaylton** [comment]
Great! thanks for the tip!

**Comment by asnowfix** [comment]
@mdobson is this issue addressed by https://github.com/apigee-internal/microgateway/releases/tag/v2.4.6-beta or should we still use that tiop?

**Comment by mdobson** [comment]
Still need to use the above.
