### ISSUE TITLE
Execute plugins for the request with invalid path

### ISSUE THREAD

**Issue by anshul07** [apigee/microgateway-core#85]
Edge Microgateway doesn't execute the plugins for the request with invalid paths. Few plugins should be executed no matter the type of request. For instance, we have written a custom plugin which processes the X-Forwarded-For header of the request to get the actual client IP but that plugin never executes for the request paths that are not configured in edgemicro_* proxies.

**Comment by srinandan** [comment]
I understand the concern. But then how do you describe "Few plugins should be executed..." in the config.yaml file? The current design specification language for microgateway (config.yaml file) is fairly simple to describe such actions.

I have a potential solution. You can create a proxy called "edgemicro_catchall" with the basePath set to "/*". All API calls will match a) the actual proxy **OR** b) the "catch all" proxy.

This solution will not work great is many cases. For ex: the OAuth plugin will always execute. It will always fail (unless you also add the catch all proxy in a product).
